config/routes.rb
Rails.application.routes.draw do
	root 'billboards#index'
	resources :billboards do
		get 'populate', on: :member
		resources :songs
	end

	# get 'billboards/populate/:id' => 'billboards#populate'
	resources :artists do
		resources :songs
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :songs, dependent: :destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
	has_many :songs
	def populate(songs=Song.all)
		songs_without = []
		songs.each do |s|
			if s.billboard_id == nil
				songs_without.push(s)
			end
		end

		@number = 0
		case rand(3)
		when 0
			@number = 50
		when 1
			@number = 25
		when 2
			@number = 100
		end
		@number.times do
			if songs_without.length == 0
				break
			end
			song = songs_without[rand(songs_without.length)]
			song.billboard_id = self.id
			song.save
			songs_without -= [song]
		end
		self.name+=" #{@number}"
		self.save
	end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
	belongs_to :billboard, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :set_artist, except: [:index, :new, :create]
	def index
		@artists = Artist.all
  end

	def show
		
	end
	
	def new
		@artist = Artist.new
	end
	def create
		@artist = Artist.new(artist_params)
		if @artist.save
			redirect_to artists_path
		else
			render :new
		end
	end
	def edit
		
	end
	def update
		if @artist.update(artist_params)
			redirect_to @artist
		else
			render :edit
		end
	end
	def destroy
		@artist.destroy
		redirect_to artists_path
	end

	private
		def set_artist
			@artist = Artist.find(params[:id])
		end

		def artist_params
			params.require(:artist).permit(:name)
		end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
	before_action :set_billboard, except: [:index, :new, :create]
	def index
		@billboards = Billboard.all
  end

  def show
	
	end

  def new
		@billboard = Billboard.new
	end

  def create
		@billboard = Billboard.new(billboard_params)
		if @billboard.save
			redirect_to @billboard
		else
			render :new
		end
	end

  def edit
		
	end

  def update
		if @billboard.update(billboard_params)
			redirect_to @billboard
		else
			render :edit
		end
	end

  def destroy
		@billboard.songs.destroy_all
		@billboard.destroy
		redirect_to billboards_path
	end

	def populate
		@billboard.populate
		redirect_to @billboard
	end
	private
		def set_billboard
			@billboard = Billboard.find(params[:id])
		end

		def billboard_params
			params.require(:billboard).permit(:name)
		end
	
end

app/controllers/song_controller.rb
class SongController < ApplicationController
	before_action :set_song, except: [:index,:new, :create]
	before_action :set_artist
	def index
		@songs = @artist.songs
	end
	def show
	end
	def new
		@song = Song.new
	end
	def create
		@song = @artist.songs.new(song_params)
		if @song.save
			redirect_to @artist
		else
			render :new
		end
	end
	def edit
	end
	def update
		if @song.update(song_params)
			redirect_to artist_song_path(@artist,@song)
		else
			render :edit
		end
	end
	def destroy
		@song.destroy
		redirect_to @artist
	end
	private
		def set_song
			@song = Song.find(params[:id])
		end
		def set_artist
			@artist = Artist.find(params[:artist_id])
		end
		def song_params
			params.require(:song).permit(:name,:genre,:length,:year)
		end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :set_song, except: [:index,:new, :create]
	before_action :set_artist
	def index
		@songs = @artist.songs
	end
	def show
	end
	def new
		@song = Song.new
	end
	def create
		@song = @artist.songs.new(song_params)
		if @song.save
			redirect_to @artist
		else
			render :new
		end
	end
	def edit
	end
	def update
		if @song.update(song_params)
			redirect_to artist_song_path(@artist,@song)
		else
			render :edit
		end
	end
	def destroy
		@song.destroy
		redirect_to @artist
	end
	private
		def set_song
			@song = Song.find(params[:id])
		end
		def set_artist
			@artist = Artist.find(params[:artist_id])
		end
		def song_params
			params.require(:song).permit(:name,:genre,:length,:year)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<hr/>
<%=form_with(model:@artist,local: true, class: "ui form") do |f|%>
	<%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
	<%= f.submit nil, class: "ui button" %>
<%end%>

app/views/artists/edit.html.erb
<h1 class="heading">Edit <%=@artist.name%> </h1>

<%= render 'form', artist: @artist %>

app/views/artists/index.html.erb
<h1 class="header">Artists</h1>
<%= link_to 'Add Artist', new_artist_path%>
<br/>
<ul>
	<% @artists.each do |artist|%>
		<li><%= link_to "#{artist.name}", artist %></li>
	<%end%>
</ul>

app/views/artists/new.html.erb
<h1 class="heading">New Artist</h1>

<%= render 'form', artist: @artist %>

app/views/artists/show.html.erb
<h1 class="header">@artist.name</h1>
<br/>
<h2>Songs</h2>
<% @artist.songs.each do |song| %>
  <%= render 'songs/song', { song: song } %>
<% end %>
<br />
<%= link_to 'Edit Artist', @artist %>
<%= link_to 'Add Artist', new_artist_path %>

app/views/billboards/_form.html.erb
<hr/>
<%=form_with(model:@billboard,local: true, class: "ui form") do |f|%>
	<%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
	<%= f.submit nil, class: "ui button" %>
<%end%>

app/views/billboards/_populate.html.erb
<% if @billboard.songs.count == 0 %>
	<h2 class="header">Empty Billboard</h2>
	<%= button_to "Populate", [:populate,@billboard], method: :get, class: "ui button red"%>
<%end%>

app/views/billboards/edit.html.erb
<h1 class="header">Edit <%=@billboard.name%></h1>

<%=render 'form', billboard: @billboard%>
<%=render 'populate', billboard: @billboard%>

app/views/billboards/index.html.erb
<h1 class="header">Billboards</h1>
<%= link_to 'New Billboard', new_billboard_path %>
<hr/>
<ul class="ui celled list">
	<% @billboards.each do |board|%>
		<div class="item"><%= link_to "#{board.name}", board %></div>
	<%end%>
</ul>

app/views/billboards/new.html.erb
<h1 class="header">New BillBoard</h1>
<%=render 'form', billboard: @billboard%>

app/views/billboards/show.html.erb
<h1 class="header"><%=@billboard.name%></h1>
<hr/>
<%= link_to 'Delete', @billboard, method: :delete, class: "ui button negative" %>
<br/>
<%= render 'populate', billboard: @billboard %>
<%@billboard.songs.each do |song|%>
	<%= render 'songs/song', { song: song } %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="ui container">
		<%= link_to 'Billboards', billboards_path, class: "ui button basic"%>
		<%= link_to 'Artists', artists_path, class: "ui button basic" %>
    <%= yield %>
  </body>
</html>

app/views/song/_song.html.erb
<hr />
<p><%= song.name %></p>
<p><%= song.length %></p>
<%= link_to 'View Full Details', artist_song_path(@artist,song) %>
<%= link_to 'View Artist', @artist %>
<hr/>

app/views/song/new.html.erb
<h1 class="header">Add A Song</h1>
<%= form_with(model: [@arist, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true, autofocus: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <br />
  <%= f.label :length %>
  <%= f.number_field :length, required: true, in:0.30..5, step: 0.01 %>
  <br />
  <br />
  <%= f.label :year %>
  <%= f.number_field :year, required: true , in:1900..2019%>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

<%= link_to 'Back', @artist %>

app/views/songs/_song.html.erb
<hr />
<%if @artist == nil%>
	<%@artist=Artist.find(song.artist_id)%>
<%end%>
<p><%= song.name %></p>
<p><%= song.length %></p>
<%= link_to 'View Full Details', artist_song_path(@artist,song) %>
<%= link_to 'View Artist', @artist %>
<hr/>

app/views/songs/new.html.erb
<h1 class="header">Add A Song</h1>
<%= form_with(model: [@arist, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true, autofocus: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <br />
  <%= f.label :length %>
  <%= f.number_field :length, required: true, in:0.30..5, step: 0.01 %>
  <br />
  <br />
  <%= f.label :year %>
  <%= f.number_field :year, required: true , in:1900..2019%>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

<%= link_to 'Back', @artist %>

app/views/songs/show.html.erb
<div class="ui card">
	<h1 class="heading"><%=@song.name%></h1>
	<h2 class="heading"><%=@artist.name%></h2>
	<br/>
	<h3 class="heading"><%=@song.genre%></h3>
	<h3 class="heading"><%=@song.year%></h3>
	<h3 class="heading"><%=@song.length%></h3>
</div>